-- PARTIAL load for public.news_stories, GENERATED from content/news.json.
--
--   npm run build:news-seed -- --only 2026-09-03 --write
--
-- ⚠️ DO NOT HAND-EDIT. Regenerate instead; this file is an output.
--
-- Run it in the Supabase SQL editor, which executes as the table owner. The
-- anon key is refused by RLS (correctly) and `service_role` is deliberately
-- unavailable to this project — see the header of scripts/build-news-seed.mjs.
--
-- ⚠️ IDEMPOTENT ON `slug`: re-running updates in place instead of duplicating.
-- `slug` is the immutable public identifier from here on; `legacy_id` is the
-- OLD positional `<date>-<index>` form that shared links still point at, and it
-- is what the 301 endpoint resolves.
--
-- Generated from 9 stories for 2026-09-03, out of 90 in the file.
--
-- ⚠️ PARTIAL. This touches ONLY the rows listed below. It is not a
-- replacement for supabase/seed/news_seed.sql and does not reconcile
-- anything it omits.

update public.news_stories set pinned = false
 where pinned and slug <> '2026-09-03-ai-helps-workers-most-when-paired-with-experience';

insert into public.news_stories
  (slug, legacy_id, story_date, sort_order, title, source, url, summary, implications, tags, pinned, status)
values
  ('2026-09-03-spot-new-tech-skills-emerging-from-the-workforce', '2026-09-03-0', '2026-09-03'::date, 0, 'Spot New Tech Skills Emerging From the Workforce', 'MIT Sloan Management Review', 'https://sloanreview.mit.edu/article/spot-new-tech-skills-emerging-from-the-workforce/', 'Field research inside an Italian furniture manufacturer adopting new production technology found that the skills workers actually developed were almost never the ones forecast in the training plan. Real capability emerged bottom-up as teams improvised to make new tools fit existing work, and it only became durable where a manager noticed it and pushed for structural changes to support it. The skills had no job descriptions and appeared in no competency framework.', 'Capability builders should treat skills taxonomies as lagging indicators during a technology rollout and build a route for emergent, improvised capability to be spotted and formalised — otherwise the most valuable skills developed go unrecognised because no framework had a name for them.', ARRAY['skills development', 'workforce transformation', 'leadership and culture', 'research and insights']::text[], false, 'published'),
  ('2026-09-03-dethroning-loyalty', '2026-09-03-1', '2026-09-03'::date, 1, 'Dethroning Loyalty', 'MIT Sloan Management Review', 'https://sloanreview.mit.edu/article/dethroning-loyalty/', 'Survey research identifies four distinct forms of workplace allegiance — coerced allegiance (compliance through fear), sycophantic allegiance (fawning for advancement), idealised devotion (mission-first, burnout-producing), and shared principled commitment (mutual respect around purpose). Only the fourth correlates with significantly higher performance. Fewer than a quarter of US employees trust leadership or believe their organisation values their wellbeing.', 'A diagnostic for leaders whose teams look committed but are running on fear, advancement-seeking or self-sacrifice — none of which surfaces in a performance review until late, and none of which an engagement score distinguishes from the real thing. Whether dissent is read as disloyalty is the tell.', ARRAY['leadership and culture', 'workforce transformation', 'research and insights']::text[], false, 'published'),
  ('2026-09-03-why-cash-rewards-dont-always-produce-better-ideas', '2026-09-03-2', '2026-09-03'::date, 2, 'Why Cash Rewards Don''t Always Produce Better Ideas', 'Harvard Business Review', 'https://hbr.org/2026/09/why-cash-rewards-dont-always-produce-better-ideas', 'Analysis of 2,376 observations of individual inventors at publicly listed Chinese firms found that identical financial incentives produced opposite behaviours depending on the inventor''s professional identity. Specialists with narrow technical focus produced fewer inventions but ones that were more novel and technically significant; generalists spanning multiple domains responded by increasing volume.', 'Incentives do not simply raise innovation, they steer what kind of innovation gets pursued — so anyone designing an innovation reward should know whether they are paying specialists or generalists, because the same scheme pulls the two toward depth and breadth respectively.', ARRAY['leadership and culture', 'skills development', 'research and insights']::text[], false, 'published'),
  ('2026-09-03-middle-managers-will-make-or-break-ai-adoption', '2026-09-03-3', '2026-09-03'::date, 3, 'Middle Managers Will Make or Break AI Adoption', 'Harvard Business Review', 'https://hbr.org/2026/09/middle-managers-will-make-or-break-ai-adoption', 'Argues the common failure point in generative AI deployment is neither strategy nor tooling but the manager layer that has to convert executive ambition into daily behaviour. Even where leadership has funded, selected and mandated AI use, managers determine whether it becomes embedded practice, a marginal experiment, a compliance chore, or quietly abandoned. Draws on McKinsey work on managers as the unlock for generative AI, and sets out five manager archetypes.', 'Relocates the pilot-to-production bottleneck to the manager layer: an AI rollout that funds licences and mandates without equipping managers is buying tooling and leaving adoption to chance. Commentary rather than primary research.', ARRAY['workforce transformation', 'leadership and culture']::text[], false, 'published'),
  ('2026-09-03-research-how-curveball-questions-can-surface-the-insight', '2026-09-03-4', '2026-09-03'::date, 4, 'Research: How Curveball Questions Can Surface the Insight You''re Looking For', 'Harvard Business Review', 'https://hbr.org/2026/09/research-how-curveball-questions-can-surface-the-insight-youre-looking-for', 'Conventional advice says to ask tough questions to get past rehearsed answers. This research finds that unexpected questions grounded in the specific context outperform generic hard-hitting ones, because rehearsed material simply doesn''t apply to them. The effect holds across interviews, performance conversations and negotiations.', 'A rare instance of the analytical-thinking and judgment cluster being operationalised into something practisable: swapping one prepared hard question for one specific, unexpected one is a cheap and immediately testable upgrade to any information-gathering conversation.', ARRAY['skills development', 'research and insights']::text[], false, 'published'),
  ('2026-09-03-which-skills-will-help-people-most-in-an-ai-driven-future', '2026-09-03-5', '2026-09-03'::date, 5, 'Which Skills Will Help People Most in an AI-Driven Future?', 'World Economic Forum', 'https://www.weforum.org/stories/artificial-intelligence/skills-people-ai-driven-future/', 'The piece contrasts divergent national approaches to AI in schools and traces the implication forward to the workforces those systems produce. Its core claim is that as access to frontier models becomes near-universal and undifferentiated, the scarce inputs shift to human judgement and originality — the parts of the work that cannot be recovered from a prompt.', 'Sharpens the AI-fluency versus AI-literacy distinction by arguing fluency commoditises and judgement does not: tool familiarity is table stakes conferring no advantage, and the capability worth protecting is forming an independent view before consulting a model.', ARRAY['skills development', 'macro signals']::text[], false, 'published'),
  ('2026-09-03-develop-your-teams-social-capital-not-just-their-skills', '2026-09-03-6', '2026-09-03'::date, 6, 'Develop Your Team''s Social Capital, Not Just Their Skills', 'MIT Sloan Management Review', 'https://sloanreview.mit.edu/article/develop-your-teams-social-capital-not-just-their-skills/', 'Qualitative research with 21 professionals across functions and career stages found that organisations systematically build technical skill and job performance while neglecting social capital — the trust, credibility and advocacy that determine whether performance becomes visible. Participants described it not as networking but as concrete organisational dynamics: who gets extended trust, whose advice is sought, who gets argued for when they are not in the room.', 'Exposes the blind spot in skills-based workforce models — a taxonomy captures capability but not the relational infrastructure that converts capability into opportunity, so a development plan that is only a list of skills leaves the variable that actually moves people to chance.', ARRAY['skills development', 'leadership and culture', 'research and insights']::text[], false, 'published'),
  ('2026-09-03-ai-helps-workers-most-when-paired-with-experience', '2026-09-03-7', '2026-09-03'::date, 7, 'AI Helps Workers Most When Paired With Experience', 'Information Systems Research (via Phys.org)', 'https://phys.org/news/2026-08-ai-workers-paired.html', 'A randomised field study of roughly 6,000 Instacart shoppers across around 160 stores found AI navigation and product-location guidance cut refund rates 3.83%, improved picking speed 3.29% and raised productivity 3.16%. The gains were concentrated among experienced workers, who selectively combined algorithmic guidance with their own judgment; less-experienced workers leaned on the system more heavily and did not consistently get better outcomes.', 'Contradicts the reading that AI levels the playing field for novices, and sharpens the capability-versus-readiness gap: the binding constraint here is human expertise rather than model quality, so deploying the tool without funding experience-building leaves most of the value unrealised.', ARRAY['skills development', 'workforce transformation', 'research and insights']::text[], true, 'published'),
  ('2026-09-03-ai-transformation-requires-redesigning-work-not-cutting', '2026-09-03-8', '2026-09-03'::date, 8, 'AI Transformation Requires Redesigning Work, Not Cutting Roles', 'Harvard Business Review', 'https://hbr.org/2026/08/ai-transformation-requires-redesigning-work-not-cutting-roles', 'The authors argue much of the current layoff wave is "AI-washing" — routine restructuring rebranded as AI-driven to read as forward-thinking to investors. They cite Goldman Sachs data putting AI''s actual drag at roughly 16,000 jobs per month of US payroll growth, about 0.1 points on unemployment, and conclude the narrative has run well ahead of the reality.', 'Gives leaders a test to apply to their own AI announcements and to those of their competitors: a plan that names headcount targets but no redesigned workflows is a cost exercise, whatever capability shift it advertises.', ARRAY['workforce transformation', 'leadership and culture']::text[], false, 'published')
on conflict (slug) do update set
  legacy_id    = excluded.legacy_id,
  story_date   = excluded.story_date,
  sort_order   = excluded.sort_order,
  title        = excluded.title,
  source       = excluded.source,
  url          = excluded.url,
  summary      = excluded.summary,
  implications = excluded.implications,
  tags         = excluded.tags,
  pinned       = excluded.pinned,
  status       = excluded.status;

-- Nothing in this batch is merged away; clear any pointer left by a
-- previous run so the file stays the source of truth.
update public.news_stories set merged_into = null
 where slug in ('2026-09-03-spot-new-tech-skills-emerging-from-the-workforce', '2026-09-03-dethroning-loyalty', '2026-09-03-why-cash-rewards-dont-always-produce-better-ideas', '2026-09-03-middle-managers-will-make-or-break-ai-adoption', '2026-09-03-research-how-curveball-questions-can-surface-the-insight', '2026-09-03-which-skills-will-help-people-most-in-an-ai-driven-future', '2026-09-03-develop-your-teams-social-capital-not-just-their-skills', '2026-09-03-ai-helps-workers-most-when-paired-with-experience', '2026-09-03-ai-transformation-requires-redesigning-work-not-cutting') and merged_into is not null;

-- Verification, to run in the same sitting:
--   select count(*) from public.news_stories
--     where story_date in ('2026-09-03');  -- expect 9
--   select count(*) from public.news_stories where pinned;           -- expect at most 1
--   select title from public.news_stories where title ~ '[^[:ascii:]]' limit 5;
--     -- eyeball these: accented text must read correctly, not as mojibake
