-- PARTIAL load for public.news_stories, GENERATED from content/news.json.
--
--   npm run build:news-seed -- --only 2026-09-03 --only 2026-09-08 --only 2026-09-09 --only 2026-09-10 --write
--
-- ⚠️ DO NOT HAND-EDIT. Regenerate instead; this file is an output.
--
-- Run it in the Supabase SQL editor, which executes as the table owner. The
-- anon key is refused by RLS (correctly) and `service_role` is deliberately
-- unavailable to this project — see the header of scripts/build-news-seed.mjs.
--
-- ⚠️ IDEMPOTENT ON `slug`: re-running updates in place instead of duplicating.
-- `slug` is the immutable public identifier from here on; `legacy_id` is the
-- OLD positional `<date>-<index>` form that shared links still point at, and it
-- is what the 301 endpoint resolves.
--
-- Generated from 14 stories for 2026-09-03, 2026-09-08, 2026-09-09, 2026-09-10, out of 98 in the file.
--
-- ⚠️ PARTIAL. This touches ONLY the rows listed below. It is not a
-- replacement for supabase/seed/news_seed.sql and does not reconcile
-- anything it omits.

update public.news_stories set pinned = false
 where pinned and slug <> '2026-09-10-gartner-identifies-4-shifts-shaping-the-future-of-work';

insert into public.news_stories
  (slug, legacy_id, story_date, sort_order, title, source, url, summary, implications, tags, pinned, status)
values
  ('2026-09-03-spot-new-tech-skills-emerging-from-the-workforce', '2026-09-03-0', '2026-09-03'::date, 0, 'Spot New Tech Skills Emerging From the Workforce', 'MIT Sloan Management Review', 'https://sloanreview.mit.edu/article/spot-new-tech-skills-emerging-from-the-workforce/', 'Field research inside an Italian furniture manufacturer adopting new production technology found that the skills workers actually developed were almost never the ones forecast in the training plan. Real capability emerged bottom-up as teams improvised to make new tools fit existing work, and it only became durable where a manager noticed it and pushed for structural changes to support it. The skills had no job descriptions and appeared in no competency framework.', 'Capability builders should treat skills taxonomies as lagging indicators during a technology rollout and build a route for emergent, improvised capability to be spotted and formalised — otherwise the most valuable skills developed go unrecognised because no framework had a name for them.', ARRAY['skills development', 'workforce transformation', 'leadership and culture', 'research and insights']::text[], false, 'published'),
  ('2026-09-03-dethroning-loyalty', '2026-09-03-1', '2026-09-03'::date, 1, 'Dethroning Loyalty', 'MIT Sloan Management Review', 'https://sloanreview.mit.edu/article/dethroning-loyalty/', 'Survey research identifies four distinct forms of workplace allegiance — coerced allegiance (compliance through fear), sycophantic allegiance (fawning for advancement), idealised devotion (mission-first, burnout-producing), and shared principled commitment (mutual respect around purpose). Only the fourth correlates with significantly higher performance. Fewer than a quarter of US employees trust leadership or believe their organisation values their wellbeing.', 'A diagnostic for leaders whose teams look committed but are running on fear, advancement-seeking or self-sacrifice — none of which surfaces in a performance review until late, and none of which an engagement score distinguishes from the real thing. Whether dissent is read as disloyalty is the tell.', ARRAY['leadership and culture', 'workforce transformation', 'research and insights']::text[], false, 'published'),
  ('2026-09-03-why-cash-rewards-dont-always-produce-better-ideas', '2026-09-03-2', '2026-09-03'::date, 2, 'Why Cash Rewards Don''t Always Produce Better Ideas', 'Harvard Business Review', 'https://hbr.org/2026/09/why-cash-rewards-dont-always-produce-better-ideas', 'Analysis of 2,376 observations of individual inventors at publicly listed Chinese firms found that identical financial incentives produced opposite behaviours depending on the inventor''s professional identity. Specialists with narrow technical focus produced fewer inventions but ones that were more novel and technically significant; generalists spanning multiple domains responded by increasing volume.', 'Incentives do not simply raise innovation, they steer what kind of innovation gets pursued — so anyone designing an innovation reward should know whether they are paying specialists or generalists, because the same scheme pulls the two toward depth and breadth respectively.', ARRAY['leadership and culture', 'skills development', 'research and insights']::text[], false, 'published'),
  ('2026-09-03-middle-managers-will-make-or-break-ai-adoption', '2026-09-03-3', '2026-09-03'::date, 3, 'Middle Managers Will Make or Break AI Adoption', 'Harvard Business Review', 'https://hbr.org/2026/09/middle-managers-will-make-or-break-ai-adoption', 'Argues the common failure point in generative AI deployment is neither strategy nor tooling but the manager layer that has to convert executive ambition into daily behaviour. Even where leadership has funded, selected and mandated AI use, managers determine whether it becomes embedded practice, a marginal experiment, a compliance chore, or quietly abandoned. Draws on McKinsey work on managers as the unlock for generative AI, and sets out five manager archetypes.', 'Relocates the pilot-to-production bottleneck to the manager layer: an AI rollout that funds licences and mandates without equipping managers is buying tooling and leaving adoption to chance. Commentary rather than primary research.', ARRAY['workforce transformation', 'leadership and culture']::text[], false, 'published'),
  ('2026-09-03-research-how-curveball-questions-can-surface-the-insight', '2026-09-03-4', '2026-09-03'::date, 4, 'Research: How Curveball Questions Can Surface the Insight You''re Looking For', 'Harvard Business Review', 'https://hbr.org/2026/09/research-how-curveball-questions-can-surface-the-insight-youre-looking-for', 'Conventional advice says to ask tough questions to get past rehearsed answers. This research finds that unexpected questions grounded in the specific context outperform generic hard-hitting ones, because rehearsed material simply doesn''t apply to them. The effect holds across interviews, performance conversations and negotiations.', 'A rare instance of the analytical-thinking and judgment cluster being operationalised into something practisable: swapping one prepared hard question for one specific, unexpected one is a cheap and immediately testable upgrade to any information-gathering conversation.', ARRAY['skills development', 'research and insights']::text[], false, 'published'),
  ('2026-09-03-which-skills-will-help-people-most-in-an-ai-driven-future', '2026-09-03-5', '2026-09-03'::date, 5, 'Which Skills Will Help People Most in an AI-Driven Future?', 'World Economic Forum', 'https://www.weforum.org/stories/artificial-intelligence/skills-people-ai-driven-future/', 'The piece contrasts divergent national approaches to AI in schools and traces the implication forward to the workforces those systems produce. Its core claim is that as access to frontier models becomes near-universal and undifferentiated, the scarce inputs shift to human judgement and originality — the parts of the work that cannot be recovered from a prompt.', 'Sharpens the AI-fluency versus AI-literacy distinction by arguing fluency commoditises and judgement does not: tool familiarity is table stakes conferring no advantage, and the capability worth protecting is forming an independent view before consulting a model.', ARRAY['skills development', 'macro signals']::text[], false, 'published'),
  ('2026-09-03-develop-your-teams-social-capital-not-just-their-skills', '2026-09-03-6', '2026-09-03'::date, 6, 'Develop Your Team''s Social Capital, Not Just Their Skills', 'MIT Sloan Management Review', 'https://sloanreview.mit.edu/article/develop-your-teams-social-capital-not-just-their-skills/', 'Qualitative research with 21 professionals across functions and career stages found that organisations systematically build technical skill and job performance while neglecting social capital — the trust, credibility and advocacy that determine whether performance becomes visible. Participants described it not as networking but as concrete organisational dynamics: who gets extended trust, whose advice is sought, who gets argued for when they are not in the room.', 'Exposes the blind spot in skills-based workforce models — a taxonomy captures capability but not the relational infrastructure that converts capability into opportunity, so a development plan that is only a list of skills leaves the variable that actually moves people to chance.', ARRAY['skills development', 'leadership and culture', 'research and insights']::text[], false, 'published'),
  ('2026-09-03-ai-helps-workers-most-when-paired-with-experience', '2026-09-03-7', '2026-09-03'::date, 7, 'AI Helps Workers Most When Paired With Experience', 'Information Systems Research (via Phys.org)', 'https://phys.org/news/2026-08-ai-workers-paired.html', 'A randomised field study of roughly 6,000 Instacart shoppers across around 160 stores found AI navigation and product-location guidance cut refund rates 3.83%, improved picking speed 3.29% and raised productivity 3.16%. The gains were concentrated among experienced workers, who selectively combined algorithmic guidance with their own judgment; less-experienced workers leaned on the system more heavily and did not consistently get better outcomes.', 'Contradicts the reading that AI levels the playing field for novices, and sharpens the capability-versus-readiness gap: the binding constraint here is human expertise rather than model quality, so deploying the tool without funding experience-building leaves most of the value unrealised.', ARRAY['skills development', 'workforce transformation', 'research and insights']::text[], false, 'published'),
  ('2026-09-03-ai-transformation-requires-redesigning-work-not-cutting', '2026-09-03-8', '2026-09-03'::date, 8, 'AI Transformation Requires Redesigning Work, Not Cutting Roles', 'Harvard Business Review', 'https://hbr.org/2026/08/ai-transformation-requires-redesigning-work-not-cutting-roles', 'The authors argue much of the current layoff wave is "AI-washing" — routine restructuring rebranded as AI-driven to read as forward-thinking to investors. They cite Goldman Sachs data putting AI''s actual drag at roughly 16,000 jobs per month of US payroll growth, about 0.1 points on unemployment, and conclude the narrative has run well ahead of the reality.', 'Gives leaders a test to apply to their own AI announcements and to those of their competitors: a plan that names headcount targets but no redesigned workflows is a cost exercise, whatever capability shift it advertises.', ARRAY['workforce transformation', 'leadership and culture']::text[], false, 'published'),
  ('2026-09-10-employees-disengaged-show-them-how-they-add-value', '2026-09-10-0', '2026-09-10'::date, 0, 'Employees Disengaged? Show Them How They Add Value', 'Harvard Business School Working Knowledge', 'https://www.library.hbs.edu/working-knowledge/employees-disengaged-show-them-how-they-add-value', 'Researchers ran a two-arm communication experiment at a 292-employee, 12-site building-materials firm after it introduced broad-based equity. Employees who got a letter naming the specific daily behaviours that build company value were 13 percentage points less likely to leave than those who got values-and-mission messaging. The effect was strongest during organisational disruption.', 'If you can''t draw the line from what you did this week to something the business actually values, that gap is a documented driver of your own disengagement — not a motivation failing. Write that line yourself if no one hands it to you, and use it in your next check-in rather than waiting for leadership to supply the narrative.', ARRAY['research and insights']::text[], false, 'published'),
  ('2026-09-10-gartner-identifies-4-shifts-shaping-the-future-of-work', '2026-09-10-1', '2026-09-10'::date, 1, 'Gartner Identifies 4 Shifts Shaping the Future of Work', 'Gartner', 'https://www.gartner.com/en/newsroom/press-releases/2026-09-09-gartner-identifies-four-shifts-shaping-the-future-of-work', 'Gartner reframes the current phase as workforce amplification rather than automation, with early AI investments entering the Trough of Disillusionment. Two of the four named shifts are expanding human capability through the human–AI relationship (strengthening judgment, creativity and decision-making while preserving accountability) and building a workforce that adapts, not just adopts. Gartner predicts that by 2029, 30% of employees laid off as AI replacements will need rehiring, often at higher cost.', '"Adapt, not adopt" is the distinction to hold onto — tool fluency is table stakes, and the differentiator is being the person who redesigns how a process runs end-to-end. If you''re in a function under displacement pressure, the rehiring forecast is a reason to document what only you can adjudicate, not to compete on speed of tool use.', ARRAY['workforce transformation', 'skills development']::text[], true, 'published'),
  ('2026-09-10-developing-and-validating-a-career-competency-framework-for', '2026-09-10-2', '2026-09-10'::date, 2, 'Developing and Validating a Career Competency Framework for the Fourth Industrial Revolution', 'Frontiers in Organizational Psychology', 'https://www.frontiersin.org/journals/organizational-psychology/articles/10.3389/forgp.2026.1823243/full', 'A two-round modified Delphi study narrowed 38 candidate competencies to 26, split into 12 critical core and 14 important contributors. The core tier: career adaptability, ethical behaviour, digital literacy, continuous learning, resilience, complex problem-solving, critical thinking, virtual collaboration, collaboration, diversity, communication and work–life integration. Notably, networking and goal-setting — staples of conventional career advice — were de-emphasised, and ethical behaviour was treated as a core competency rather than an add-on.', 'Check your development plan against that core tier before adding another tool certification — adaptability and judgment rank above the specialised capabilities most plans lead with. If you''ve been treating networking as the main lever on your career, this panel of practitioners who actually made 4IR transitions ranked it below the ability to keep learning and to reason through messy problems.', ARRAY['skills development', 'research and insights']::text[], false, 'published'),
  ('2026-09-09-ai-can-enhance-every-stage-of-teamwork-under-two-conditions', '2026-09-09-0', '2026-09-09'::date, 0, 'AI Can Enhance Every Stage of Teamwork—Under Two Conditions', 'Harvard Business Review', 'https://hbr.org/2026/09/ai-can-enhance-every-stage-of-teamwork-under-two-conditions', 'Drawing on work with more than 300 managers across 35 organizations, the authors argue that most AI deployment treats the tool as a solo productivity aid and ignores the collaborative arc entirely. They map AI to three distinct stages: before a meeting to sharpen preparation and pressure-test ideas, during it to challenge assumptions and broaden perspectives, and after it to force reflection and convert lessons into reusable practice. The gains depend on two conditions — intentionality and craft — not on tool access.', 'If your AI use stops at drafting your own work, you''re leaving the higher-value application untouched — try using it to pressure-test your position before your next contentious meeting, and to interrogate what actually happened after one. Notice which of the three stages you never use it for; that gap is where the compounding return sits.', ARRAY['skills development', 'workforce transformation', 'leadership and culture']::text[], false, 'published'),
  ('2026-09-08-ai-could-undermine-managers-judgement-unless-used-carefully', '2026-09-08-0', '2026-09-08'::date, 0, 'AI Could Undermine Managers'' Judgement Unless Used Carefully, University of Bath-Led Study Warns', 'University of Bath', 'https://www.bath.ac.uk/announcements/ai-could-undermine-managers-judgement-unless-used-carefully-university-of-bath-led-study-warns/', 'The paper theorises two opposing pathways for what generative AI does to phronesis — the practical wisdom built through experience, reflection and human interaction. "Epistemic deskilling" happens when people outsource enough of their thinking that they stop exercising their own judgement; "epistemic upskilling" happens when AI is used as a prompt for reflection. The decisive variable is accountability: where people must justify and explain their reasoning to others, AI use tends to deepen judgement rather than replace it.', 'Change what you ask AI for — instead of an answer, ask it to argue against your position, then find the gaps in its reasoning, because those gaps are exactly where your own judgement has to do the work. If nobody currently asks you to justify your decisions, build that structure yourself: write down your reasoning before you prompt, and compare.', ARRAY['skills development', 'research and insights']::text[], false, 'published')
on conflict (slug) do update set
  legacy_id    = excluded.legacy_id,
  story_date   = excluded.story_date,
  sort_order   = excluded.sort_order,
  title        = excluded.title,
  source       = excluded.source,
  url          = excluded.url,
  summary      = excluded.summary,
  implications = excluded.implications,
  tags         = excluded.tags,
  pinned       = excluded.pinned,
  status       = excluded.status;

-- Nothing in this batch is merged away; clear any pointer left by a
-- previous run so the file stays the source of truth.
update public.news_stories set merged_into = null
 where slug in ('2026-09-03-spot-new-tech-skills-emerging-from-the-workforce', '2026-09-03-dethroning-loyalty', '2026-09-03-why-cash-rewards-dont-always-produce-better-ideas', '2026-09-03-middle-managers-will-make-or-break-ai-adoption', '2026-09-03-research-how-curveball-questions-can-surface-the-insight', '2026-09-03-which-skills-will-help-people-most-in-an-ai-driven-future', '2026-09-03-develop-your-teams-social-capital-not-just-their-skills', '2026-09-03-ai-helps-workers-most-when-paired-with-experience', '2026-09-03-ai-transformation-requires-redesigning-work-not-cutting', '2026-09-10-employees-disengaged-show-them-how-they-add-value', '2026-09-10-gartner-identifies-4-shifts-shaping-the-future-of-work', '2026-09-10-developing-and-validating-a-career-competency-framework-for', '2026-09-09-ai-can-enhance-every-stage-of-teamwork-under-two-conditions', '2026-09-08-ai-could-undermine-managers-judgement-unless-used-carefully') and merged_into is not null;

-- Verification, to run in the same sitting:
--   select count(*) from public.news_stories
--     where story_date in ('2026-09-03', '2026-09-08', '2026-09-09', '2026-09-10');  -- expect 14
--   select count(*) from public.news_stories where pinned;           -- expect at most 1
--   select title from public.news_stories where title ~ '[^[:ascii:]]' limit 5;
--     -- eyeball these: accented text must read correctly, not as mojibake
