-- PARTIAL load for public.news_stories, GENERATED from content/news.json.
--
--   npm run build:news-seed -- --only 2026-09-15 --only 2026-09-16 --only 2026-09-18 --only 2026-09-19 --only 2026-09-21 --only 2026-09-22 --write
--
-- ⚠️ DO NOT HAND-EDIT. Regenerate instead; this file is an output.
--
-- Run it in the Supabase SQL editor, which executes as the table owner. The
-- anon key is refused by RLS (correctly) and `service_role` is deliberately
-- unavailable to this project — see the header of scripts/build-news-seed.mjs.
--
-- ⚠️ IDEMPOTENT ON `slug`: re-running updates in place instead of duplicating.
-- `slug` is the immutable public identifier from here on; `legacy_id` is the
-- OLD positional `<date>-<index>` form that shared links still point at, and it
-- is what the 301 endpoint resolves.
--
-- Generated from 11 stories for 2026-09-15, 2026-09-16, 2026-09-18, 2026-09-19, 2026-09-21, 2026-09-22, out of 111 in the file.
--
-- ⚠️ PARTIAL. This touches ONLY the rows listed below. It is not a
-- replacement for supabase/seed/news_seed.sql and does not reconcile
-- anything it omits.

insert into public.news_stories
  (slug, legacy_id, story_date, sort_order, title, source, url, summary, implications, tags, pinned, status)
values
  ('2026-09-22-research-work-stress-isnt-always-about-workload', '2026-09-22-0', '2026-09-22'::date, 0, 'Research: Work Stress Isn''t Always About Workload', 'Harvard Business Review', 'https://hbr.org/2026/09/research-work-stress-isnt-always-about-workload', 'Gargi Sawhney and Mallory McCord write up their meta-analysis of 60 years of role-stressor research: 515 studies covering 787,959 workers. Unclear expectations (role ambiguity) proved the most damaging stressor overall, eroding job satisfaction and performance; clashing demands (role conflict) were the main driver of burnout and quitting; and sheer overload mostly produced emotional and physical symptoms. The usual fixes, such as moving tasks around or time-management training, only address overload.', 'When work starts to feel crushing, work out which of the three it is before you ask for help. If the real problem is unclear expectations, ask your manager to say plainly what "done" and "good" look like — that will likely do more for your performance than getting a task taken off your plate.', ARRAY['leadership and culture', 'research and insights']::text[], false, 'published'),
  ('2026-09-22-workplace-ai-adoption-remains-slow-informal-and-uneven', '2026-09-22-1', '2026-09-22'::date, 1, 'Workplace AI Adoption Remains Slow, Informal and Uneven (Konstanz AI Study, Wave 3)', 'University of Konstanz (via Phys.org)', 'https://phys.org/news/2026-09-workplace-ai-uneven-survey.html', 'A May 2026 survey of 1,105 German employees by the University of Konstanz Future of Work Lab finds only 38% use AI at work, up from 35% a year earlier, and just 55% of users say their main tool was introduced by their employer. Use splits sharply: 49% of knowledge workers against 25% of manual workers, and 56% of highly educated employees against 21% of those with less education. Among small organisations, only 11% offer AI training and 10% have usage guidelines.', 'Don''t wait for a formal rollout. In most workplaces AI skill is being built by employees on their own initiative, and waiting widens the gaps above. Keep a record of what you try — prompts, workflows, limits you hit — so that when official policy arrives you''re the one helping to shape it.', ARRAY['workforce transformation', 'skills development', 'research and insights']::text[], false, 'published'),
  ('2026-09-21-research-gen-ai-is-collapsing-creative-processes', '2026-09-21-0', '2026-09-21'::date, 0, 'Research: Gen AI Is Collapsing Creative Processes', 'Harvard Business Review', 'https://hbr.org/2026/09/research-gen-ai-is-collapsing-creative-processes', 'A Netherlands-based team spent a year observing senior creative professionals in TV and advertising production. Generative AI sped up brainstorming but squeezed the stages where ideas normally get checked against what can actually be made. In one case a client approved an AI-generated image whose lighting was physically impossible, and the production team then had to try to recreate it.', 'Treat AI speed at the idea stage as a debt you pay later, unless your own expertise checks the work first. Add a feasibility check between an AI draft and showing it to anyone, and state plainly what reality can deliver — your hands-on knowledge of the constraints becomes more valuable, not less.', ARRAY['skills development', 'workforce transformation', 'research and insights']::text[], false, 'published'),
  ('2026-09-19-almost-every-job-has-tasks-that-ai-can-change-brynjolfsson', '2026-09-19-0', '2026-09-19'::date, 0, '"Almost Every Job Has Tasks That AI Can Change": Brynjolfsson on What Actually Protects Workers', 'Stanford Graduate School of Business', 'https://www.gsb.stanford.edu/insights/almost-every-job-has-tasks-ai-can-change', 'Erik Brynjolfsson argues almost no job is fully automatable but almost every job has tasks AI can change, and that what protects workers is framing good questions and owning the outcome — AI fluency alone is like email fluency in 2005. He cites a 19% employment gap for 22–25-year-olds in AI-exposed jobs, and a study of 51 AI deployments in which 77% of problems were non-technical (change management, data quality, process redesign) and only 45% of deployments reduced headcount.', 'List your tasks in two columns — ones AI could replace and ones it could improve — then deliberately move your time toward the second before someone else decides for you. Early in your career, go after the judgment, checking and client-facing work that remains once routine junior tasks are automated.', ARRAY['skills development', 'workforce transformation', 'macro signals']::text[], false, 'published'),
  ('2026-09-18-how-ai-creates-a-capability-mirage', '2026-09-18-0', '2026-09-18'::date, 0, 'How AI Creates a Capability Mirage', 'MIT Sloan Management Review', 'https://sloanreview.mit.edu/article/how-ai-creates-a-capability-mirage/', 'Drawing on a joint Anthrome Insight–Axialent study of how AI affects behaviour and culture at work, the authors argue that because generative AI lets anyone produce polished output, organisations look capable while real skills quietly wear away. Teammates can no longer tell what a colleague actually understands, and trust between them suffers.', 'Polished output no longer shows that you can do the work. Look for chances to show your reasoning live — talk through the trade-offs, defend a draft without the tool, or teach someone else — and keep practising the core skills you currently hand off to AI, so they don''t fade without you noticing.', ARRAY['skills development', 'workforce transformation']::text[], false, 'published'),
  ('2026-09-18-employers-look-for-resilient-staff-then-leave-them-to-burn', '2026-09-18-1', '2026-09-18'::date, 1, 'Employers Look for Resilient Staff – Then Leave Them to Burn Out', 'The Conversation', 'https://theconversation.com/employers-look-for-resilient-staff-then-leave-them-to-burn-out-290463', 'Laura Chamberlain of Warwick Business School reports that hiring managers name resilience as the quality that decides whether a new hire succeeds, yet organisations rarely develop it and instead wait to see who survives a crisis. Drawing on her interviews and wider research, she argues resilience is built through relationships rather than individual toughness, and has to be built in calm periods. This is research-informed commentary rather than a new study, and the author runs a resilience-training business.', 'Build your support network now, while things are calm: colleagues who notice early when you''re struggling, and people who make it OK to ask for help. Separate "can''t" from "not yet" by keeping a list of the tasks you''ve deferred.', ARRAY['skills development', 'leadership and culture']::text[], false, 'published'),
  ('2026-09-16-what-it-takes-to-make-progress-when-the-future-feels-out-of', '2026-09-16-0', '2026-09-16'::date, 0, 'What It Takes to Make Progress When the Future Feels Out of Control', 'Harvard Business Review IdeaCast', 'https://hbr.org/podcast/2026/09/what-it-takes-to-make-progress-when-the-future-feels-out-of-control', 'Martin Seligman argues agency is made of three separable components — efficacy (belief you can hit a goal now), optimism (belief effort pays off long-term) and imagination (the breadth of goals you can envision) — and that all three respond to training rather than being fixed traits. He positions abductive reasoning, the creative inferential leap, as the human capability AI does not replicate.', 'When you catch yourself concluding a project or a market is hopeless, put it in perspective — worst case, best case, most likely case — then plan against the most likely one. Treating pessimism as a testable hypothesis rather than a read on reality is the habit that separates people who keep making moves from people who wait.', ARRAY['skills development']::text[], false, 'published'),
  ('2026-09-16-stop-automating-old-processes-design-new-ones-instead', '2026-09-16-1', '2026-09-16'::date, 1, 'Stop Automating Old Processes. Design New Ones Instead.', 'Harvard Business Review', 'https://hbr.org/2026/09/stop-automating-old-processes-design-new-ones-instead', 'Organisations are doubling AI spend (BCG: 0.8% to 1.7% of revenue), yet only 12% of CEOs report both revenue and cost benefits (PwC), and 60% see no enterprise-wide EBIT impact despite around 80% using generative AI somewhere (McKinsey QuantumBlack). Masha Shunko and Serguei Netessine attribute the gap to automating existing tasks inside unchanged workflows rather than redesigning the workflow first.', 'If you''re asked to bolt AI onto a process you already run, the higher-value contribution is mapping what that process would look like if designed today from scratch — redesign judgment is scarcer than tool proficiency. Notice whether your organisation measures AI adoption or AI outcomes; the answer tells you how long the current approach has.', ARRAY['workforce transformation', 'leadership and culture']::text[], false, 'published'),
  ('2026-09-16-you-think-youre-a-good-collaborator-do-the-people-you-manage', '2026-09-16-2', '2026-09-16'::date, 2, 'You Think You''re a Good Collaborator. Do the People You Manage Agree?', 'Harvard Business Review', 'https://hbr.org/2026/09/you-think-youre-a-good-collaborator-do-the-people-you-manage-agree', 'Drawing on data from more than 10,000 professionals, Ivan Matviak and Heidi K. Gardner find senior leaders consistently rate themselves as effective collaborators who listen and empower, while the people they work with report otherwise. Dominating conversations and micromanaging are named as the behaviours that most undercut leaders'' intended collaborative posture.', 'If your manager describes the team as collaborative in terms you wouldn''t use, the gap is well documented rather than a sign you''re misreading things — and specific behavioural feedback travels better than a rating. The moment you lead anything, assume your own self-assessment is the least reliable data point available.', ARRAY['leadership and culture', 'research and insights']::text[], false, 'published'),
  ('2026-09-15-even-a-tiny-sense-of-lasting-meaning-makes-people-choose', '2026-09-15-0', '2026-09-15'::date, 0, 'Even a Tiny Sense of Lasting Meaning Makes People Choose Harder Work — Starting by Age Four', 'Psychological Science', 'https://doi.org/10.1177/09567976261462874', 'Across four experiments with 604 children aged 4–9 and 582 adults, researchers from UT Dallas and the University of Chicago found that when told their work would be kept, 83% of adults chose the challenging creative task; told it would be destroyed, only 34% did. Making the task more fun raised motivation somewhat but could not make up for knowing the work wouldn''t last.', 'Notice which parts of your work feel thrown away — drafts nobody reads, analyses that go nowhere — and build a way for that work to last, such as a decision log, a shared doc or a reusable template. You''ll be more willing to take on hard problems when your effort visibly adds up.', ARRAY['research and insights']::text[], false, 'published'),
  ('2026-09-15-career-shocks-and-the-sustainability-of-global-careers', '2026-09-15-1', '2026-09-15'::date, 1, 'Career Shocks and the Sustainability of Global Careers', 'International Journal of Human Resource Management', 'https://www.tandfonline.com/doi/full/10.1080/09585192.2026.2723321', 'A University of Western Australia study followed more than 150 expatriates through personal, organisational and institutional shocks — from divorce and restructures to downturns and immigration policy. Those who reset their goals, learned new skills, widened their networks or moved again ended up with satisfying long-run careers; those who waited it out did not. Company-sponsored expats responded proactively more often, largely because they had internal mobility and support to draw on.', 'When a restructure or life event knocks your plan off course, treat it as a prompt to review your direction rather than something to recover from quietly. Before the next shock arrives, work out which internal networks and mobility options you could actually use — especially if you don''t have organisational sponsorship.', ARRAY['skills development', 'workforce transformation', 'research and insights']::text[], false, 'published')
on conflict (slug) do update set
  legacy_id    = excluded.legacy_id,
  story_date   = excluded.story_date,
  sort_order   = excluded.sort_order,
  title        = excluded.title,
  source       = excluded.source,
  url          = excluded.url,
  summary      = excluded.summary,
  implications = excluded.implications,
  tags         = excluded.tags,
  pinned       = excluded.pinned,
  status       = excluded.status;

-- Nothing in this batch is merged away; clear any pointer left by a
-- previous run so the file stays the source of truth.
update public.news_stories set merged_into = null
 where slug in ('2026-09-22-research-work-stress-isnt-always-about-workload', '2026-09-22-workplace-ai-adoption-remains-slow-informal-and-uneven', '2026-09-21-research-gen-ai-is-collapsing-creative-processes', '2026-09-19-almost-every-job-has-tasks-that-ai-can-change-brynjolfsson', '2026-09-18-how-ai-creates-a-capability-mirage', '2026-09-18-employers-look-for-resilient-staff-then-leave-them-to-burn', '2026-09-16-what-it-takes-to-make-progress-when-the-future-feels-out-of', '2026-09-16-stop-automating-old-processes-design-new-ones-instead', '2026-09-16-you-think-youre-a-good-collaborator-do-the-people-you-manage', '2026-09-15-even-a-tiny-sense-of-lasting-meaning-makes-people-choose', '2026-09-15-career-shocks-and-the-sustainability-of-global-careers') and merged_into is not null;

-- Verification, to run in the same sitting:
--   select count(*) from public.news_stories
--     where story_date in ('2026-09-15', '2026-09-16', '2026-09-18', '2026-09-19', '2026-09-21', '2026-09-22');  -- expect 11
--   select count(*) from public.news_stories where pinned;           -- expect at most 1
--   select title from public.news_stories where title ~ '[^[:ascii:]]' limit 5;
--     -- eyeball these: accented text must read correctly, not as mojibake
